/**
 * Builds `tokens.json` into the three consumed artifacts:
 *
 *   generated/tokens.css        → imported by `app/globals.css` (Tailwind v4 @theme)
 *   generated/tokens.ts         → sRGB hex, for widgets that cannot parse OKLCH
 *   generated/RectoTokens.swift → SwiftUI `Color` accessors (plan 023 design §5)
 *   generated/Colors.xcassets   → light/dark colorsets the Swift accessors read
 *
 * Outputs are COMMITTED: the Apple side has no Bun at build time, so the Swift
 * package consumes the generated files straight from the repo. `tokens.test.ts`
 * rebuilds into a temp dir and fails if the committed files have drifted.
 *
 * Run: `bun run tokens:build`
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { clampChroma, formatHex, parse } from "culori";
import StyleDictionary from "style-dictionary";

const HERE = dirname(fileURLToPath(import.meta.url));

/** A DTCG leaf after Style Dictionary has parsed it. */
type Leaf = { $value?: string; value?: string; $description?: string };
type Leaves = Record<string, Leaf>;
/** A palette: named groups of leaves, plus DTCG string metadata like `$description`. */
type Group = Record<string, Leaves | string>;
/** Every palette in `tokens.json`, keyed by name. */
type Palettes = Record<string, Group>;
/** A colour resolved into the sRGB form Apple and Clerk need. */
type Srgb = { hex: string; alpha: number };

/**
 * Which palettes are complete and which appearance each belongs to. This is
 * structure, not design value — the values all live in `tokens.json`.
 * `twilight` seeds Tailwind's `@theme`; every other palette is emitted as an
 * override of it.
 */
const DARK_ONLY_PALETTES = ["aurora", "dawn", "moonlit"] as const;
const BASE_PALETTE = "twilight";
const LIGHT_PALETTE = "paper";

/**
 * CSS custom-property prefix per token group. `color` lands in Tailwind's
 * `--color-*` namespace so `bg-bg-app` and friends keep working; the rest are
 * plain variables read through `var()` in `globals.css`.
 */
const CSS_PREFIX: Record<string, string> = {
	color: "--color-",
	atmosphere: "--",
	elevation: "--elevation-",
	grain: "--grain-",
};

/**
 * Tokens that cross to Apple, with their SwiftUI accessor and asset-catalog
 * names (plan 023 design §5). Naming is a platform concern, so it lives here
 * rather than polluting every palette in `tokens.json`. Only `color` tokens
 * cross: shadows, blend modes and the atmosphere gradients are rebuilt natively.
 */
const NATIVE_NAMES = {
	"bg-app": { swift: "rectoCanvas", asset: "RectoCanvas" },
	"bg-surface": { swift: "rectoSheet", asset: "RectoSheet" },
	"bg-raised": { swift: "rectoRaised", asset: "RectoRaised" },
	"bg-overlay": { swift: "rectoOverlay", asset: "RectoOverlay" },
	"bg-hover": { swift: "rectoHover", asset: "RectoHover" },
	"ink-primary": { swift: "rectoInk", asset: "RectoInk" },
	"ink-secondary": { swift: "rectoInk2", asset: "RectoInk2" },
	"ink-tertiary": { swift: "rectoInk3", asset: "RectoInk3" },
	"on-accent": { swift: "rectoOnAccent", asset: "RectoOnAccent" },
	line: { swift: "rectoLine", asset: "RectoLine" },
	"line-strong": { swift: "rectoLineStrong", asset: "RectoLineStrong" },
	accent: { swift: "rectoAccent", asset: "RectoAccent" },
	"accent-muted": { swift: "rectoAccentMuted", asset: "RectoAccentMuted" },
	"accent-2": { swift: "rectoAccent2", asset: "RectoAccent2" },
	"accent-wash": { swift: "rectoAccentWash", asset: "RectoAccentWash" },
	success: { swift: "rectoOk", asset: "RectoOk" },
	warning: { swift: "rectoWarn", asset: "RectoWarn" },
	danger: { swift: "rectoDanger", asset: "RectoDanger" },
	"lint-passive": { swift: "rectoLintPassive", asset: "RectoLintPassive" },
	"lint-readability": {
		swift: "rectoLintReadability",
		asset: "RectoLintReadability",
	},
	"lint-adverb": { swift: "rectoLintAdverb", asset: "RectoLintAdverb" },
	"lint-weasel": { swift: "rectoLintWeasel", asset: "RectoLintWeasel" },
	comment: { swift: "rectoComment", asset: "RectoComment" },
	"comment-wash": { swift: "rectoCommentWash", asset: "RectoCommentWash" },
	"comment-wash-strong": {
		swift: "rectoCommentWashStrong",
		asset: "RectoCommentWashStrong",
	},
	selection: { swift: "rectoSelection", asset: "RectoSelection" },
	"focus-ring": { swift: "rectoFocusRing", asset: "RectoFocusRing" },
	caret: { swift: "rectoCaret", asset: "RectoCaret" },
} satisfies Record<string, { swift: string; asset: string }>;

const HEADER = (source: string) =>
	`Generated by packages/design-tokens/build.ts from ${source}. Do not edit — edit the source and run \`bun run tokens:build\`.`;

function leafValue(leaf: Leaf): string {
	const value = leaf.$value ?? leaf.value;
	if (typeof value !== "string") {
		throw new Error(`token has no string $value: ${JSON.stringify(leaf)}`);
	}
	return value;
}

/**
 * Style Dictionary hands formats and actions a loosely-typed token tree. This is
 * the single place that pins it to the shape `tokens.json` actually has.
 */
function readPalettes(dictionary: { tokens?: unknown }): Palettes {
	const root = dictionary.tokens;
	// SAFETY: narrowed to a non-null object on the line above; reading an absent
	// `palette` off it yields undefined, which the next check rejects.
	const palettes =
		root && typeof root === "object"
			? (root as { palette?: unknown }).palette
			: undefined;
	if (!palettes || typeof palettes !== "object") {
		throw new Error("tokens.json has no `palette` root");
	}
	// SAFETY: checked above that `palette` is an object; every leaf below is
	// re-checked by `leafValue`, which throws when a `$value` is missing.
	return palettes as Palettes;
}

function paletteGroups(palettes: Palettes, palette: string): Group {
	const group = palettes[palette];
	if (!group) throw new Error(`tokens.json has no palette "${palette}"`);
	return group;
}

/** The `color` group of a palette. */
function paletteColors(palettes: Palettes, palette: string): Leaves {
	const colors = paletteGroups(palettes, palette).color;
	if (!colors || typeof colors === "string") {
		throw new Error(`palette "${palette}" has no color group`);
	}
	return colors;
}

/** One token's value, named in the error so a typo in `tokens.json` is obvious. */
function colorValue(colors: Leaves, token: string, palette: string): string {
	const leaf = colors[token];
	if (!leaf) {
		throw new Error(`palette "${palette}" is missing the "${token}" token`);
	}
	return leafValue(leaf);
}

/** `[cssVariableName, value]` for every leaf in a palette, in declaration order. */
function cssPairs(group: Group): [string, string][] {
	const pairs: [string, string][] = [];
	for (const [groupName, entries] of Object.entries(group)) {
		const prefix = CSS_PREFIX[groupName];
		// `$description` and other DTCG metadata sit alongside the groups.
		if (!prefix || typeof entries === "string") continue;
		for (const [name, leaf] of Object.entries(entries)) {
			if (name.startsWith("$")) continue;
			pairs.push([`${prefix}${name}`, leafValue(leaf)]);
		}
	}
	return pairs;
}

function block(selector: string, group: Group, comment: string): string {
	const body = cssPairs(group)
		.map(([name, value]) => `\t${name}: ${value};`)
		.join("\n");
	return `/* ${comment} */\n${selector} {\n${body}\n}\n`;
}

StyleDictionary.registerFormat({
	name: "recto/css",
	format: ({ dictionary }) => {
		const palettes = readPalettes(dictionary);
		const parts = [
			`/* ${HEADER("packages/design-tokens/tokens.json")} */\n`,
			block(
				"@theme",
				paletteGroups(palettes, BASE_PALETTE),
				`Twilight (dark) is the base palette. It lives in @theme so Tailwind generates\n   the colour utilities (bg-bg-app, text-ink-primary, …) from it.`,
			),
			...DARK_ONLY_PALETTES.map((name) =>
				block(
					`:root[data-theme="${name}"]`,
					paletteGroups(palettes, name),
					`${name[0]?.toUpperCase()}${name.slice(1)} — dark-only palette; only the tokens that differ from Twilight.`,
				),
			),
			block(
				":root:not(.dark)",
				paletteGroups(palettes, LIGHT_PALETTE),
				`Paper (light). LAST ON PURPOSE: this selector has the same specificity (0,2,0)\n   as the :root[data-theme=…] blocks above, so source order is what makes Paper win\n   when a dark palette is still stored and the appearance resolves to light.`,
			),
		];
		return parts.join("\n");
	},
});

StyleDictionary.registerFormat({
	name: "recto/swift",
	format: ({ dictionary }) => {
		const palettes = readPalettes(dictionary);
		const light = paletteColors(palettes, LIGHT_PALETTE);
		const dark = paletteColors(palettes, BASE_PALETTE);
		const lines = Object.entries(NATIVE_NAMES).map(([token, names]) => {
			const doc = `\t/// ${colorValue(dark, token, BASE_PALETTE)} (dark) · ${colorValue(light, token, LIGHT_PALETTE)} (light)`;
			return `${doc}\n\tstatic let ${names.swift} = Color("${names.asset}", bundle: .module)`;
		});
		return [
			`// ${HEADER("packages/design-tokens/tokens.json")}`,
			"//",
			"// The values live in Colors.xcassets next to this file, so the system resolves",
			"// light/dark (and Increase Contrast, once variants are added) for us. Add both",
			"// files to the same SwiftPM target's resources for `.module` to resolve.",
			"",
			"import SwiftUI",
			"",
			"public extension Color {",
			lines.join("\n\n"),
			"}",
			"",
		].join("\n");
	},
});

/**
 * Third-party widgets that parse colours themselves (Clerk) cannot take OKLCH,
 * so the opaque tokens are also emitted as sRGB hex per appearance. Alpha-
 * carrying tokens are skipped: a wash only means anything composited over a
 * known layer, which is a CSS job.
 */
StyleDictionary.registerFormat({
	name: "recto/ts",
	format: ({ dictionary }) => {
		const palettes = readPalettes(dictionary);
		const table = (paletteName: string) => {
			const colors = paletteColors(palettes, paletteName);
			return Object.entries(colors)
				.map(([name, leaf]) => [name, toSrgb(leafValue(leaf))] as const)
				.filter(([, { alpha }]) => alpha === 1)
				.map(([name, { hex }]) => `\t\t"${name}": "${hex}",`)
				.join("\n");
		};
		return [
			`// ${HEADER("packages/design-tokens/tokens.json")}`,
			"",
			"/** Opaque palette tokens as sRGB hex, for consumers that cannot parse OKLCH. */",
			"export const RECTO_HEX = {",
			"\tdark: {",
			table(BASE_PALETTE),
			"\t},",
			"\tlight: {",
			table(LIGHT_PALETTE),
			"\t},",
			"} as const;",
			"",
		].join("\n");
	},
});

/** OKLCH → sRGB hex + alpha, gamut-mapped by reducing chroma (culori). */
function toSrgb(value: string): Srgb {
	const parsed = parse(value);
	if (!parsed) throw new Error(`unparseable colour: ${value}`);
	const hex = formatHex(clampChroma(parsed, "oklch", "rgb"));
	if (!hex) throw new Error(`colour has no sRGB hex form: ${value}`);
	return { hex, alpha: parsed.alpha ?? 1 };
}

function colorsetJson(lightValue: string, darkValue: string): string {
	const entry = (value: string, dark: boolean) => {
		const { hex, alpha } = toSrgb(value);
		// A colorset's first entry is "Any Appearance"; only the second carries the
		// `appearances` discriminator that makes it the Dark variant.
		const appearances = dark
			? [{ appearance: "luminosity", value: "dark" }]
			: undefined;
		return {
			appearances,
			color: {
				"color-space": "srgb",
				components: {
					alpha: alpha.toFixed(3),
					blue: `0x${hex.slice(5, 7).toUpperCase()}`,
					green: `0x${hex.slice(3, 5).toUpperCase()}`,
					red: `0x${hex.slice(1, 3).toUpperCase()}`,
				},
			},
			idiom: "universal",
		};
	};
	return `${JSON.stringify(
		{
			colors: [entry(lightValue, false), entry(darkValue, true)],
			info: { author: "xcode", version: 1 },
		},
		null,
		2,
	)}\n`;
}

function assetRoot(buildPath: string | undefined): string {
	if (!buildPath) throw new Error("the xcassets action needs a buildPath");
	return buildPath;
}

StyleDictionary.registerAction({
	name: "recto/xcassets",
	do: async (dictionary, platform) => {
		const palettes = readPalettes(dictionary);
		const light = paletteColors(palettes, LIGHT_PALETTE);
		const dark = paletteColors(palettes, BASE_PALETTE);
		const root = join(assetRoot(platform.buildPath), "Colors.xcassets");
		await rm(root, { recursive: true, force: true });
		await mkdir(root, { recursive: true });
		await writeFile(
			join(root, "Contents.json"),
			`${JSON.stringify({ info: { author: "xcode", version: 1 } }, null, 2)}\n`,
		);
		for (const [token, names] of Object.entries(NATIVE_NAMES)) {
			const dir = join(root, `${names.asset}.colorset`);
			await mkdir(dir, { recursive: true });
			await writeFile(
				join(dir, "Contents.json"),
				colorsetJson(
					colorValue(light, token, LIGHT_PALETTE),
					colorValue(dark, token, BASE_PALETTE),
				),
			);
		}
	},
	undo: async (_dictionary, platform) => {
		await rm(join(assetRoot(platform.buildPath), "Colors.xcassets"), {
			recursive: true,
			force: true,
		});
	},
});

/** Builds every artifact into `buildPath` (defaults to the committed `generated/`). */
export async function buildTokens(
	buildPath = join(HERE, "generated"),
): Promise<void> {
	const sd = new StyleDictionary({
		source: [join(HERE, "tokens.json")],
		log: { verbosity: "silent", warnings: "disabled" },
		platforms: {
			// No transforms anywhere: OKLCH strings, shadow lists and blend modes are
			// passed through verbatim to CSS, and converted with culori (not Style
			// Dictionary) where Apple needs sRGB components.
			css: {
				transforms: [],
				buildPath: `${buildPath}/`,
				files: [
					{
						destination: "tokens.css",
						format: "recto/css",
						options: { showFileHeader: false },
					},
				],
			},
			ts: {
				transforms: [],
				buildPath: `${buildPath}/`,
				files: [
					{
						destination: "tokens.ts",
						format: "recto/ts",
						options: { showFileHeader: false },
					},
				],
			},
			swift: {
				transforms: [],
				buildPath: `${buildPath}/`,
				files: [
					{
						destination: "RectoTokens.swift",
						format: "recto/swift",
						options: { showFileHeader: false },
					},
				],
				actions: ["recto/xcassets"],
			},
		},
	});
	await sd.buildAllPlatforms();
}

if (import.meta.main) {
	await buildTokens();
}
