/**
 * Slices the vim core out of `@replit/codemirror-vim`'s published bundle.
 *
 * The upstream bundle is already split the way we need: `initVim(CM)` is a
 * ~7,000-line factory that receives the editor adapter *class* as its only
 * argument and returns the vim API. Every editor call it makes goes through
 * that argument, so the core carries no CodeMirror 6 reference at all — the 7
 * CM6 references in the package all sit below the seam, in the adapter and the
 * view plugin, which we replace wholesale.
 *
 * So the "patch" against upstream is a cut, not an edit: we copy the factory
 * out verbatim, byte for byte. Nothing in the core is rewritten, which is why
 * a version bump is a re-run of this script rather than a merge.
 *
 * `StringStream` gets the same treatment from `@codemirror/language`: the core
 * asks for it as `CM.StringStream` (ex-command argument parsing), and the class
 * is self-contained, so we copy it rather than pull the whole language package
 * — which would drag DOM-touching code into a JavaScriptCore bundle.
 *
 * Run: `bun run vim:extract` (implied by `bun run vim:build`).
 */

const VIM_PKG = "@replit/codemirror-vim";
const EXPECTED_VIM_VERSION = "6.3.0";
const LANG_PKG = "@codemirror/language";

/** Cut the text between two unique anchors, failing loudly if either drifts. */
function sliceBetween(
	source: string,
	startAnchor: string,
	endAnchor: string,
	what: string,
): string {
	const starts = countOccurrences(source, startAnchor);
	const ends = countOccurrences(source, endAnchor);
	if (starts !== 1 || ends !== 1) {
		throw new Error(
			`${what}: anchors are no longer unique (start x${starts}, end x${ends}). ` +
				`Upstream layout changed; re-read the bundle and update the anchors.`,
		);
	}
	const from = source.indexOf(startAnchor);
	const to = source.indexOf(endAnchor);
	if (to <= from) {
		throw new Error(`${what}: end anchor precedes start anchor.`);
	}
	return source.slice(from, to + endAnchor.length);
}

/** Cut from a unique anchor up to (not including) the next unique boundary. */
function sliceUntil(
	source: string,
	startAnchor: string,
	endBoundary: string,
	what: string,
): string {
	const starts = countOccurrences(source, startAnchor);
	const ends = countOccurrences(source, endBoundary);
	if (starts !== 1 || ends !== 1) {
		throw new Error(
			`${what}: anchors are no longer unique (start x${starts}, boundary x${ends}). ` +
				`Upstream layout changed; re-read the bundle and update the anchors.`,
		);
	}
	const from = source.indexOf(startAnchor);
	const to = source.indexOf(endBoundary);
	if (to <= from) {
		throw new Error(`${what}: boundary precedes start anchor.`);
	}
	return source.slice(from, to).trimEnd();
}

function countOccurrences(haystack: string, needle: string): number {
	let count = 0;
	let index = haystack.indexOf(needle);
	while (index !== -1) {
		count++;
		index = haystack.indexOf(needle, index + needle.length);
	}
	return count;
}

async function readPackage(name: string): Promise<{ version: string; dir: string }> {
	const manifestPath = Bun.resolveSync(`${name}/package.json`, import.meta.dir);
	const manifest = await Bun.file(manifestPath).json();
	return { version: manifest.version, dir: manifestPath.replace(/\/package\.json$/, "") };
}

const vim = await readPackage(VIM_PKG);
if (vim.version !== EXPECTED_VIM_VERSION) {
	// Not fatal: the seam has been stable across 6.x. But the anchors below are
	// verified against one version, so make the operator look at the diff.
	console.warn(
		`WARNING: ${VIM_PKG} is ${vim.version}, extraction verified against ${EXPECTED_VIM_VERSION}.\n` +
			`  Re-check the anchors and re-run the keystroke suite before trusting the bundle.`,
	);
}

const vimBundle = await Bun.file(`${vim.dir}/dist/index.js`).text();
const core = sliceBetween(
	vimBundle,
	"function initVim(CM) {",
	"\n  return vimApi;\n}",
	"vim core",
);

// `scanForBracket` (for `%` and the `i(`/`a{` text objects) and `hardWrap` (for
// `gq`) are written against the adapter interface, not against CM6 — upstream
// keeps them beside the adapter only because that is where they are wired up.
// They are usable verbatim, so extract rather than re-implement.
const helpers = sliceUntil(
	vimBundle,
	'var matching = { "(": ")>",',
	"function findMatchingTag(cm, pos) {",
	"bracket helpers",
);
const hardWrap = sliceUntil(
	vimBundle,
	"function hardWrap(cm, options) {",
	"\n// backwards compatibility for old versions",
	"hardWrap",
);

const lang = await readPackage(LANG_PKG);
const langBundle = await Bun.file(`${lang.dir}/dist/index.js`).text();
const stringStream = sliceBetween(
	langBundle,
	"class StringStream {",
	"current() { return this.string.slice(this.start, this.pos); }\n}",
	"StringStream",
);

const header =
	`// GENERATED by scripts/extract-core.ts — do not edit.\n` +
	`// Verbatim slices of ${VIM_PKG}@${vim.version} and ${LANG_PKG}@${lang.version}.\n` +
	`// Both are MIT licensed; see LICENSE-THIRD-PARTY.md.\n`;

const outDir = `${import.meta.dir}/../src/generated`;
await Bun.write(
	`${outDir}/vim-core.js`,
	`${header}\n/* eslint-disable */\nexport ${core}\n`,
);
await Bun.write(
	`${outDir}/string-stream.js`,
	`${header}\n/* eslint-disable */\nexport ${stringStream}\n`,
);
// The helper slices reference the bare identifier `Pos`. Prepending an import
// keeps the extracted bodies byte-identical to upstream.
await Bun.write(
	`${outDir}/vim-helpers.js`,
	`${header}\n/* eslint-disable */\nimport { Pos } from "../pos.js";\n\n` +
		`${helpers}\n\nexport ${hardWrap}\n\nexport { scanForBracket };\n`,
);

const lineCount = (s: string) => s.split("\n").length;
console.log(
	`extracted vim core:     ${lineCount(core)} lines (${VIM_PKG}@${vim.version})\n` +
		`extracted helpers:      ${lineCount(helpers) + lineCount(hardWrap)} lines (same bundle)\n` +
		`extracted StringStream: ${lineCount(stringStream)} lines (${LANG_PKG}@${lang.version})\n` +
		`edits applied to upstream source: 0`,
);
