/**
 * Writes the canonical Markdown corpus (`lib/markdown/corpus/cases.ts`) out as
 * one `.md` file per case, for the Swift snapshot tests to read.
 *
 * The web corpus is the source of truth for the dialect; Swift cannot import
 * TypeScript, so the files are checked in and regenerated by this script. Run
 * it whenever a case is added or changed:
 *
 *     bun apple/Packages/RectoEditor/Tools/make-corpus.ts
 *
 * When `packages/editor-fixtures/markdown-corpus.json` (W3) lands, point this
 * at that instead — the output contract (numbered `NN-slug.md` files) stays.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CORPUS_CASES } from "../../../../lib/markdown/corpus/cases";

const outDir = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"Tests",
	"RectoEditorTests",
	"Corpus",
);

const slug = (name: string) =>
	name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "");

await mkdir(outDir, { recursive: true });
for (const stale of await readdir(outDir)) {
	if (stale.endsWith(".md")) await rm(join(outDir, stale));
}

for (const testCase of CORPUS_CASES) {
	const file = `${String(testCase.id).padStart(2, "0")}-${slug(testCase.name)}.md`;
	await writeFile(join(outDir, file), testCase.input, "utf8");
}

console.log(`wrote ${CORPUS_CASES.length} cases to ${outDir}`);
