#!/usr/bin/env bash
# Generates Config/Local.xcconfig (gitignored) from the environment.
#
#   CLERK_PUBLISHABLE_KEY=pk_test_… CONVEX_URL=https://…convex.cloud \
#     apple/Spikes/NativeSpike/scripts/write-local-config.sh
set -euo pipefail

: "${CLERK_PUBLISHABLE_KEY:?set CLERK_PUBLISHABLE_KEY}"
: "${CONVEX_URL:?set CONVEX_URL}"

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$dir/Config/Local.xcconfig"

# xcconfig reads "//" as start-of-comment anywhere in a value, so the scheme
# separator has to come from $(RECTO_SLASH).
escaped_url="${CONVEX_URL//\/\//\$(RECTO_SLASH)\$(RECTO_SLASH)}"

cat > "$out" <<EOC
// Generated by scripts/write-local-config.sh. Gitignored. Do not commit.
RECTO_CLERK_PUBLISHABLE_KEY = $CLERK_PUBLISHABLE_KEY
RECTO_CONVEX_DEPLOYMENT_URL = $escaped_url
EOC

echo "wrote $out"
