import { dirname, join } from "node:path";

import { characterEntities } from "character-entities";

const packageRoot = join(import.meta.dir, "..");
const outputPath = join(
  packageRoot,
  "Sources/RectoCoreJS/GeneratedHTML5CharacterEntities.swift",
);
const modulePath = Bun.resolveSync("character-entities", import.meta.dir);
const packageJSON = await Bun.file(join(dirname(modulePath), "package.json")).json();

function swiftString(value: string): string {
  return [...value]
    .map((character) => {
      const scalar = character.codePointAt(0);
      if (scalar === undefined) throw new Error("character has no Unicode scalar");
      if (character === "\\") return "\\\\";
      if (character === '"') return '\\"';
      if (scalar >= 0x20 && scalar <= 0x7e) return character;
      return `\\u{${scalar.toString(16).toUpperCase()}}`;
    })
    .join("");
}

const entries = Object.entries(characterEntities)
  .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
  .map(([name, value]) => `        "${name}": "${swiftString(value)}",`)
  .join("\n");

const generated = `// Generated by Scripts/generate-character-entities.ts from character-entities@${packageJSON.version}.
// Do not edit. Run the generator after changing the dependency.

enum GeneratedHTML5CharacterEntities {
    static let named: [String: String] = [
${entries}
    ]
}
`;

if (process.argv.includes("--check")) {
  const committed = await Bun.file(outputPath).text();
  if (committed !== generated) {
    console.error(
      "GeneratedHTML5CharacterEntities.swift is stale. Run `bun Scripts/generate-character-entities.ts` from apple/Packages/RectoCoreJS.",
    );
    process.exit(1);
  }
} else {
  await Bun.write(outputPath, generated);
}
